### ISSUE TITLE
Cache always returned "MISS"

### ISSUE THREAD

**Issue by tibor8472** [gpt4thewin/docker-nginx-openai-api-cache#1]
Never returned HIT in response even though I sent exactly the same request.
I've added the following option key - value pairs into server, then cache returns HIT after the second request:
`
proxy_ignore_headers "Set-Cookie";
proxy_hide_header "Set-Cookie";

`
Reference: [https://stackoverflow.com/questions/9230812/nginx-as-cache-proxy-not-caching-anything](url)

**Comment by artificial-julien** [comment]
Initial request ?
Follow up request ?
Curl format please
(with keys hidden)

**Comment by langchain4j** [comment]
Can confirm, without 
```
proxy_ignore_headers "Set-Cookie";
proxy_hide_header "Set-Cookie";
```
it is always `MISS`.
Please update config.

**Comment by artificial-julien** [comment]
> Initial request ? Follow up request ? Curl format please (with keys hidden)

**Comment by langchain4j** [comment]
`MISS` on initial is expected, but it happens on follow-ups as well.

Sorry, no curl, I am sending from java okhttp client:
```
- method: POST
- url: http://.../v1/chat/completions
- headers: [Authorization: Bearer ...]
- body: {
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "user",
      "content": "tell me a joke"
    }
  ],
  "temperature": 0.7
}
```

**Comment by artificial-julien** [comment]
That's correct. Nginx does not cache response that contains "Set-Header".
Will fix
Thank you for reporting the issue and providing the fix
