### ISSUE TITLE
Get Error code: 404

### ISSUE THREAD

**Issue by FilJed** [gpt4thewin/docker-nginx-openai-api-cache#2]
Hi!
I'm trying to implement your solution, but keep getting 404
Here is log:
`NotFoundError: Error code: 404 - {'error': {'type': 'invalid_request_error', 'code': 'unknown_url', 'message': 'Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.', 'param': None}}`

It says request is wrong, but how to fix it?

**Comment by artificial-julien** [comment]
Can you provide the curl or the full request ?
It seems your request is being passed upstream but is simply wrong
